### ISSUE TITLE
Excel sample expects a specific binding

### ISSUE THREAD

**Issue by rob-williams** [OfficeDev/Office-Add-in-Commands-Samples#1]
![image](https://cloud.githubusercontent.com/assets/2903406/11668320/19e35580-9dbc-11e5-8be5-b02755d514e2.png)

It looks like a binding is selected when the Excel sample app starts up. Should there be a workbook included in the repo? I'd like to see the commands in action.

I'm on the Dynamics AX Office Integration team and my alias is rowill.

Thanks!

**Comment by LezaMax** [comment]
Hey Rob. Yes, it expects a specific binding. You have to press the "Get Data" button first before clicking the "Compare data" button.  We should make the sample better in that regard. I'll assign to @ruoyingl

**Comment by rob-williams** [comment]
Though I haven't clicked anything. The application opens with that error and no command buttons are added to the ribbon.

**Comment by ChrisGarty** [comment]
Yeah error message when running from VS. And it would be great to remove the breakpoints as well :)

**Comment by rob-williams** [comment]
![image](https://cloud.githubusercontent.com/assets/2903406/11669779/037ad8ce-9dc4-11e5-90bd-468cb66ab9da.png)

Ah, I forgot to apply the registry key! However, after applying it the add-in refuses to open and all I get is the above error.

Any ideas? I have the latest Dogfood installation, 16.0.6366.2036

**Comment by LezaMax** [comment]
@rob-williams are you deploying from VS?  I'm pretty sure the sample works if you manually side load the manifest from github and point to the already deployed webapp. I let @ruoyingl know there might be issues with VS though, I haven't tried that route myself.

**Comment by rob-williams** [comment]
Yes, I am debugging by F5 deploying from Visual Studio 2015. What do you mean by "side load?"

**Comment by LezaMax** [comment]
I mean deploying via a file share as indicated on the Readme. Here is a link that shows you how to use a network share to side load manifests: https://msdn.microsoft.com/EN-US/library/office/fp123503.aspx

**Comment by LezaMax** [comment]
Closing. As mentioned on instructions the add-in needs to be sideloaded via fileshare.
