### ISSUE TITLE
with Windows 10, the Registery setting is not working!

### ISSUE THREAD

**Issue by allwinac** [OfficeDev/Office-Add-in-Commands-Samples#11]
I have recently upgraded my OS to windows 10. before this i was using windows 7, and i download the registry setting and was able to see the ribbon control in my office 2016. 

now even after updating the Registry with windows 10. Not able to see the ribbon control in my word

**Comment by LezaMax** [comment]
Could you please share the Office build number and windows build number you are using?

**Comment by LezaMax** [comment]
@allwinac, could you share the info?  Are you still seeing this error. Please note that the core feature no longer requires a registry key for it to work with the latest builds of Office available.
