### ISSUE TITLE
SimpleAddin.xml does not load Ribbon in Excel for Mac

### ISSUE THREAD

**Issue by jonasrk** [OfficeDev/Office-Add-in-Commands-Samples#14]
Hi,

I wanted to start building an Add-In for Excel but the sample does not load the Ribbon in Microsoft Excel for Mac Version 15.23.2 (160624). The Task-Pane is showing but not the ribbon.

In Excel Online, it works fine.

I have confirmed this issue on two separate machines.

It would be super nice to have this working as I want to build a custom ribbon for my Add-In. Thanks!

PS: I had initially stated that it was not working in Excel Online as well. This was because I had forgotten (for the second time) to change the two instances of `Document` to `Workbook`. My problem with the ribbon not showing in the local installation remains.

**Comment by jonasrk** [comment]
It looks like Office for Mac simply is not supported yet. In that case I would like to ask: Can you give an estimate of when it will be?

**Comment by LezaMax** [comment]
I cannot provide you with concrete dates right now but Mac support is definitively on the roadmap as a high priority for us.

**Comment by dvm-shlee** [comment]
Hi @LezaMax, just wondering it is still not working because the sideloaded manifest of SimpleAddin is not showing any custom generated tap on my Mac.
Thank you!

**Comment by LezaMax** [comment]
Hi. Please check this article on further information on Commands for Mac. They are currently in preview but you need to follow the instructions:  https://github.com/OfficeDev/Office-Add-in-Commands-Samples/blob/master/Tools/MacDevPreview.md
