### ISSUE TITLE
Trying to load the Excel Add-In manifest into Excel online says manifest is invalid

### ISSUE THREAD

**Issue by jonasrk** [OfficeDev/Office-Add-in-Commands-Samples#15]

**Comment by darul75** [comment]
Same here, with no details on both Desktop/Online version...so disappointed and frustrated.

**Comment by darul75** [comment]
![capture d ecran 2016-08-08 a 18 13 09](https://cloud.githubusercontent.com/assets/2134003/17487148/d74de684-5d93-11e6-956f-a34ae200dbd9.png)

Sorry but trying to find all day long what is wrong, following tutorial, repositories with example but ribbon never showing on Desktop Mac version and Online version only giving me this error. Can you add details on client side about what is wrong in manifest please ? (Valid with schemas)

**Comment by darul75** [comment]
Finally found where error came from with help of this procedure (works for Desktop Windows Version only): 

https://github.com/OfficeDev/Office-Add-in-Commands-Samples/blob/master/Tools/RuntimeLogging.md

A missing tooltip resource in LongStrings...

Please add something for Online version (+ Mac version) to apply manifest validation.

**Comment by LezaMax** [comment]
We do need better diagnostic info.  Just to double check, are you unblocked now? Was there an error on a sample provided or was it in your own manifest and the lack of details on the error made it painful to figure out?

**Comment by darul75** [comment]
Second option yes, a mistake in our own manifest and no easy way to fix it. But resolved at the end.

**Comment by LezaMax** [comment]
Glad you resolved it.
