### ISSUE TITLE
SimpleAddin.xml works in Excel online but not in Excel on Windows.

### ISSUE THREAD

**Issue by jonasrk** [OfficeDev/Office-Add-in-Commands-Samples#16]
It loads so Task Pane but not the Ribbon.

The only two modifications I did to the xml file are replacing 2 instances of Document with Workbook.

Microsoft Excel 2016 MSO (16.0.4266.1003) 32-Bit
Windows 10

Tested on two machines.

**Comment by LezaMax** [comment]
Sorry it took so long to get back you. You probably noticed this already but the build required is higher than what you posted.  https://github.com/OfficeDev/Office-Add-in-Commands-Samples
