### ISSUE TITLE
Cannot run OData sample ..

### ISSUE THREAD

**Issue by syncimprov** [OfficeDev/Office-Add-in-Commands-Samples#18]
OData Metadata URL  (in web.config) is returning 500 error:

http://services.odata.org/V3/(S(dez1exxooqnc34ng5z0yil0f))/OData/OData.svc/$metadata

This is causing "Get Data" to fail. Please advice.

**Comment by LezaMax** [comment]
Should be working now. Let us know if that is not the case.

**Comment by Rick-Kirkham** [comment]
This has been pending user response for over a week, so closing.
