### ISSUE TITLE
Argument of type '{ cells: { row: number; column: number; }; format: { backgroundColor: string; }; }' is not assignable to parameter of type '{ cells: { row: number; }; format: { backgroundColor: string; }; }'

### ISSUE THREAD

**Issue by jthake** [OfficeDev/Office-Add-in-Commands-Samples#2]
I'm using Visual Studio 2015 Update 1 (TypeScript 1.7.4.0) and getting an error when compiling the Excel demo

Severity    Code    Description Project File    Line    Suppression State
Error       Build: Argument of type '{ cells: { row: number; column: number; }; format: { backgroundColor: string; }; }' is not assignable to parameter of type '{ cells: { row: number; }; format: { backgroundColor: string; }; }'.   ODSampleDataWeb C:\git\Office-Add-in-Commands-Samples\Excel\Webapp\ODSampleDataWeb\Scripts\App\Record.ts    157

**Comment by rob-williams** [comment]
I had the same issue and fixed it by changing the format variable declaration from

`var format = [{ cells: { row: rowId }, format: { backgroundColor: "#FFFACD" } }];`

to

`var format = [{ cells: { row: rowId, column: undefined }, format: { backgroundColor: "#FFFACD" } }];`

so that column is explicitly included in the original object definition.

I will send a pull request tomorrow for this change, unless there's a better way to work around TypeScript's type system.

**Comment by jthake** [comment]
If I make it 

`var format = [{ cells: { row: rowId }, format: { backgroundColor: "#FFFACD" } }];`

My project compiles. What version of Visual Studio is this being tested in? I belivee that this is the same error as the project located at https://github.com/OfficeDev/OData-Excel-Integration-Add-In-Sample that STILL is broken too.

**Comment by rob-williams** [comment]
What change did you make? I feel like I'm missing something - yours looks identical to the original.

**Comment by jthake** [comment]
the one in source control is
`var format = [{ cells: { row: rowId, column: undefined }, format: { backgroundColor: "#FFFACD" } }];`
I changed it to
`var format = [{ cells: { row: rowId }, format: { backgroundColor: "#FFFACD" } }];`

**Comment by rob-williams** [comment]
https://github.com/OfficeDev/Office-Add-in-Commands-Samples/blob/master/Excel/Webapp/ODSampleDataWeb/Scripts/App/Record.ts#L152

`var format = [{ cells: { row: rowId }, format: { backgroundColor: "#FFFACD" } }];`

is what's in source control. The "column: undefined" is what fixed it for me.

**Comment by LezaMax** [comment]
Hi the sample main purpose on this repo is to point out how commands are modeled on the Ribbon, which is why they point to an already deployed instance of that particular Add-in.
