### ISSUE TITLE
writeText from FunctionFile.html  does nothing

### ISSUE THREAD

**Issue by davidjohnbell** [OfficeDev/Office-Add-in-Commands-Samples#20]
Hey everyone,
     I am currently building my own addin using visual studio. I have created a simple manifest with three buttons. The first two go to separate task pane html and the third button should execute the function writeText from the function file but does not. the function file points to a local copy of https://commandsimple.azurewebsites.net/FunctionFile.html.
In the manifest it looks like https://localhost:44322/App/Home/FunctionFile.html
any hints?

**Comment by LezaMax** [comment]
Hey David, some things to try:

- There is a [FAQ ](https://github.com/OfficeDev/Office-Add-in-Commands-Samples/blob/master/FAQ.md)document with some hints to debug. 
- If the above doesn't help please ask your question on stackoverflow.com; that is the best resource to get help on programming questions for add-ins. Please tag your question **office-js**
