### ISSUE TITLE
SimpleAddin Not Loading, but myHelloWorldaddin works

### ISSUE THREAD

**Issue by johnyradio** [OfficeDev/Office-Add-in-Commands-Samples#21]
Hi
I'm able to install and run the myHelloWorldaddin Excel addin described here:
https://dev.office.com/docs/add-ins/get-started/create-an-office-add-in-using-any-editor

But, i cannot run your SimpleAddin.xml. 
I do not see the addin listed in Word or Excel. 

I executed the command you give for both Word and Excel: ` defaults write com.microsoft.... etc`
And i placed the file in the wef folder, according to the Sideload instructions. 

I am running Office 16: version 15.31 (170216). 
Do i still need to Get the Office Insider Fast build to use your SimpleAddin?

thx

**Comment by Rick-Kirkham** [comment]
Thanks. We'll try to reproduce this problem soon and report back here.

**Comment by LezaMax** [comment]
Thanks for the heads up. Commands for the Mac is currently in the process of rolling through different rings. Yes, at this point you do need to be part of Insiders Fast (or slow) to use the feature.
