### ISSUE TITLE
One CommandBar for multiple hosts

### ISSUE THREAD

**Issue by ndeeH** [OfficeDev/Office-Add-in-Commands-Samples#23]
When looking at the VersionOverrides Hosts - I suppose that I have to repeat myself, when using the same commands for excel, word, etc.
Or is there a chance to define a command set for multiple clients.
@LezaMax

**Comment by Rick-Kirkham** [comment]
You have to repeat the markup for each host. This is the nature of XML. There really isn't a way to assign an XML blob to a variable and then reference it in multiple places.
