### ISSUE TITLE
We can't start this add-in because it isn't set up properly

### ISSUE THREAD

**Issue by jthake** [OfficeDev/Office-Add-in-Commands-Samples#3]
I'm getting an error in the Task Pane when I F5 the Excel sample. This is after I worked around the #2 issue.
It appears in the manifest that everything is hardcoded to an environment URL https://odsample.azurewebsites.net/ which seems to require authentication shouldn't it all be pointing to the web site in the project?

**Comment by rob-williams** [comment]
I found the same error after applying the registry fix as well:

https://github.com/OfficeDev/Office-Add-in-Commands-Samples/issues/1#issuecomment-163030522

**Comment by LezaMax** [comment]
Deploying via VS is not supported yet. You have to use a network share to load your add-in.

**Comment by LezaMax** [comment]
Closing as by design. The add-in must be deployed via fileshare during the preview.
