### ISSUE TITLE
Sample manifests don't pass validation

### ISSUE THREAD

**Issue by marianatuma** [OfficeDev/Office-Add-in-Commands-Samples#31]
I'm trying to understand the deployment of add ins, but the samples don't seem to be working. I grabbed the Excel sample manifest, replaced the ID with one generated by Visual Studio, saved as an .xml file and ran `validate-office-addin` on it. The first error was a missing support URL:

```
> validate-office-addin .\sample_manifest.xml
Calling validation service. This might take a moment...
-------------------------------------
Validation: Failed

Error #1:
Missing Support URL: The manifest support URL could not be found. (link: https://aka.ms/oacksupporturl)
-------------------------------------
```

I copied the SupportURL element from [this page](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?tabs=tabid-1), ran the validator again and got this error:

```
> validate-office-addin .\sample_manifest.xml
Calling validation service. This might take a moment...
-------------------------------------
Validation: Failed

Error #1:
XML Schema Violation: Your manifest does not adhere to the current set of XML schema definitions for Office Add-in manifests. (link: https://aka.ms/add-in-manifest-schema-violation)
  - Details: The element 'OfficeApp' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1' has invalid child element 'IconUrl' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1'. List of possible elements expected: 'AppDomains, Hosts, Requirements, DefaultSettings' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1'.
  - Line: 17
  - Column: 4
-------------------------------------
```

Deleted the IconURL tag and got this:

```
> validate-office-addin .\sample_manifest.xml
Calling validation service. This might take a moment...
-------------------------------------
Validation: Failed

Error #1:
Manifest Icon Element Missing: An icon element could not be found. Please see https://aka.ms/oackicon for details. (link: https://aka.ms/oackicon)
-------------------------------------
```

The [documentation ](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/iconurl?view=office-js)for IconURL didn't help much, as it doesn't specify the parent tag. 

I had the exact same problems with the simple add in manifest. 

Are these code samples outdated? If not, why aren't they working? I'd imagine the simplest code sample from Microsoft themselves would at least pass validation.

Forgot to add, I'm on Windows 10, developing for Office365 Business. I couldn't find the version of `validate-office-addin` because it doesn't have `-v` or `--version` flags, and `-h` only lists `-h` as possible flag.

**Comment by Rick-Kirkham** [comment]
@marianatuma I think the code sample was not ever tested with the validate-office-addin tool. For purposes of developing and debugging locally, the sample should work with the original manifest anyway. Typically, you would only need to validate the manifest before deploying the add-in to production. 

The errors you are getting are misleading. The real problem with the IconUrl element was probably the order it was in relative to its peer elements within the parent OfficeApp element. To find the correct sequence the elements should be in, see this documentation: [HowHow to find the proper order of manifest elements](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering).
