### ISSUE TITLE
Possibility to add standard Word buttons

### ISSUE THREAD

**Issue by igordevjspy** [OfficeDev/Office-Add-in-Commands-Samples#33]
Would be great if we could add standard Word buttons on our custom tabs. 
It is possible to add it manually through Ribbon And Toolbar menu, but not directly through our manifest. 

Thanks, 
Igor

**Comment by Rick-Kirkham** [comment]
That's a great suggestion. I encourage you to vote for it at [Office Development Platform suggestion box, Able to add Office build-in groups controls to custom tabs](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/37106293-able-to-add-office-built-in-groups-controls-to-cus).
