### ISSUE TITLE
Outlook samples?

### ISSUE THREAD

**Issue by vijaypemmaraju** [OfficeDev/Office-Add-in-Commands-Samples#34]
Add-in commands are definitely supported in Outlook based on parts of the [documentation](https://docs.microsoft.com/en-us/outlook/add-ins/addin-tutorial), so it would be great to hav some Outlook-specific examples in this repo.

**Comment by Rick-Kirkham** [comment]
We have an Outlook sample that uses Add-in Commands at [Outlook Add-in Command Demo](https://github.com/OfficeDev/outlook-add-in-command-demo). Will this serve your needs?

**Comment by Rick-Kirkham** [comment]
@vijaypemmaraju
I'm going to close this due to inactivity. Let us know if the sample doesn't work.
