### ISSUE TITLE
Is there a way to add a command to the application menu(s) ? 

### ISSUE THREAD

**Issue by nickjgentile** [OfficeDev/Office-Add-in-Commands-Samples#35]
<img width="850" alt="Screen Shot 2019-09-10 at 3 59 22 PM" src="https://user-images.githubusercontent.com/28357364/64650277-69a5f980-d3e4-11e9-8bcb-58c42c2aaa24.png">

What I am attempting to do: add to the application's file-menu so that below `Export...` there would be an `Export to [my application's name]` menu-item that would then open my web-add-in in the taskpane. 

It looks like currently context menus and ribbon menus allow for you to create buttons/items within them to prompt the opening of your add-in, but I cannot find any way via the documentation to do what I am asking for. Is that possible?

Thanks,

**Comment by Rick-Kirkham** [comment]
No. I'm afraid that you can't modify existing menus.

**Comment by nickjgentile** [comment]
Okay, thanks for the response! Perhaps a feature request if it is not something that was previously/considered+ruled out?
