### ISSUE TITLE
Incorrect manifest file

### ISSUE THREAD

**Issue by prakhar-pal** [OfficeDev/Office-Add-in-Commands-Samples#36]
In my current project I'm trying to add a custom tab by taking XML changes from Simple/Manifest directory, I verified the changed manifest using `npm run validate`
And the log said it was correct.

But when I try to sideload this modified XML, the web app for MS word, I'm unable to sideload as the web app says that manifest is invalid.

How do I debug this?

**Comment by Rick-Kirkham** [comment]
I'm going to close this for inactivity, but you can ask to reopen it.
