### ISSUE TITLE
Need a simpler sample to illustrate the basics

### ISSUE THREAD

**Issue by LezaMax** [OfficeDev/Office-Add-in-Commands-Samples#4]
Our current samples are ok to get started but it would be better to have a simpler, bare bones example that illustrates: 
Controls: Button, Menu
ExtensionPoints: PrimaryCommandSurface and ContextMenu.
Actions: ShowTaskpane and ExecuteFunction

**Comment by ChrisGarty** [comment]
Agreed!

**Comment by LezaMax** [comment]
Added! https://github.com/OfficeDev/Office-Add-in-Commands-Samples/tree/master/Simple
