### ISSUE TITLE
Commands in Project

### ISSUE THREAD

**Issue by nnyegaard** [OfficeDev/Office-Add-in-Commands-Samples#40]
Hi,

I am trying to develop an add-in for Project, specifically a Command (I want a custom group in the toolbar with some buttons), but I am a bit unsure if that is actually possible or not. I got the task panel to work, but I have not found a way to get commands to work. Is this possible in Project?

**Comment by Rick-Kirkham** [comment]
Sorry, but no. Project does not support customization of the ribbon with add-ins. Specifically, it does not support the `<VersionOverrides>` element in the add-in manifest. The latter is needed because custom groups and buttons in the ribbon are created by child markup inside the `<VersionOverrides>` element.

**Comment by nnyegaard** [comment]
Yeah that was my thinking. Do you know if that is planned? It feels like add-ins are the future of Office development so I am a bit reluctant to start creating new projects with the old model, but maybe a hybrid where I could trigger the add-in, would that be possible? @Rick-Kirkham

**Comment by Rick-Kirkham** [comment]
We haven't invested in expanding the add-in model for Project for several years and I don't see that changing soon. There just aren't very many people creating add-ins for Project. I don't think I understand what you mean by a hybrid that could trigger the add-in.

**Comment by nnyegaard** [comment]
Sorry let me try to explain a bit better with Hybrid. Would it be possible to trigger an add-in from VSTO?

E.g. I would create a toolbar in C# that would have the buttons I want and that would open op the add-in taskbar

**Comment by Rick-Kirkham** [comment]
I don't think that would be possible. But you could try asking that question on the office-js repo Issues.
