### ISSUE TITLE
MsProject

### ISSUE THREAD

**Issue by puentesdiaz** [OfficeDev/Office-Add-in-Commands-Samples#41]
Is possible, make a Button for open my Addin, over MsProject 2019 ? (Office Desktop , Build 14026.20246)

**Comment by davidchesnut** [comment]
Hi @puentesdiaz,

Sorry, but add-in commands are not support on Microsoft Project. BTW: These samples have moved (and were updated) to https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/office-add-in-commands. This repo will be archived so if you have follow-up questions or suggestions can you please post them to https://github.com/OfficeDev/PnP-OfficeAddins/issues?

Thanks!
David
