### ISSUE TITLE
The actual length is greater than the MaxLength value

### ISSUE THREAD

**Issue by OfficeDeveloper1** [OfficeDev/Office-Add-in-Commands-Samples#7]
The resid for a Label has a maximum length of 32 characters.
Could this be increased to at least 64 characters please.

```
        <CustomTab id="MyCustomTab">
          <Label resid="01234567890123456789012345678901"/>
        </CustomTab>
```

**Comment by LezaMax** [comment]
Thanks you for the input @OfficeDeveloper1 . We can consider this but that might result in really long Tab names. Do you have a couple of examples (in English or other languages) that would require this?

**Comment by OfficeDeveloper1** [comment]
Hi LezaMax, Thank you for the reply. I am really excited about this new add-in model. To try and help my understanding I wanted to use very explicit resid's with long text descriptions.

The example below shows a long resid for the SupertipDescription which exceeds 32 characters in length.

Supertip
Title resid="res_ShortStrings_SupertipTitle"/
Description resid="res_LongStrings_SupertipDescription"/
/Supertip

bt:LongStrings
bt:String id="res_LongStrings_Description" DefaultValue="Addin Description" /
bt:String id="res_LongStrings_SupertipDescription" DefaultValue="Supertip Description"/
/bt:LongStrings

Are the resid's only used for linking the resources to the elements ?

**Comment by LezaMax** [comment]
Yes @OfficeDeveloper1, they are only used to link to resource elements.  The length of all resids attributes is the same irrespective of which resource type they are linking to.

**Comment by LezaMax** [comment]
No plans to address this right now. Closing.
