### ISSUE TITLE
Invalid add-in manifest

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/Office-Add-in-Commands-Samples#8]
The is an extra <Label> element in the ImageSample.xml manifest file between the </group> and </OfficeTab> tags. Like this: 
97               </Group> 
98               <Label resid="residLabel4" /> 
99             </OfficeTab> 
This is not a valid place for a <Label>. The manifest won't validate and in VS, the sample won't build.

**Comment by LezaMax** [comment]
Will take a look

**Comment by LezaMax** [comment]
Fixed it. It did have an extra Label element in there. The manifest ran ok on the desktop clients but you are correct that it doesn't conform to the schema as it should (it may fail in other clients).  Anyway, removed the invalid element. Thanks for pointing this out
