### ISSUE TITLE
Please add support for content add-in with commands

### ISSUE THREAD

**Issue by marcfilion** [OfficeDev/Office-Add-in-Commands-Samples#9]
The actual web addin model is nice but very limited
It would be very usefull to be able to launch content addin from add-in command.

**Comment by LezaMax** [comment]
This is something we are actively considering. Do you mind @marcfilion to add your request to UserVoice too? It can help raise visibility. https://officespdev.uservoice.com/ 

Thank you!

**Comment by LezaMax** [comment]
Closing this issue here. The request is noted :)  Please log it on uservoice if possible as it will have more visibility that way.
